
package com.guness.CardRegistery.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CardApi", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://52.28.91.8/CardApi.svc?wsdl")
public class CardApi
    extends Service
{

    private final static URL CARDAPI_WSDL_LOCATION;
    private final static WebServiceException CARDAPI_EXCEPTION;
    private final static QName CARDAPI_QNAME = new QName("http://tempuri.org/", "CardApi");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://52.28.91.8/CardApi.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARDAPI_WSDL_LOCATION = url;
        CARDAPI_EXCEPTION = e;
    }

    public CardApi() {
        super(__getWsdlLocation(), CARDAPI_QNAME);
    }

    public CardApi(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARDAPI_QNAME, features);
    }

    public CardApi(URL wsdlLocation) {
        super(wsdlLocation, CARDAPI_QNAME);
    }

    public CardApi(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARDAPI_QNAME, features);
    }

    public CardApi(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardApi(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICardApi
     */
    @WebEndpoint(name = "BasicHttpBinding_ICardApi")
    public ICardApi getBasicHttpBindingICardApi() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ICardApi"), ICardApi.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICardApi
     */
    @WebEndpoint(name = "BasicHttpBinding_ICardApi")
    public ICardApi getBasicHttpBindingICardApi(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ICardApi"), ICardApi.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARDAPI_EXCEPTION!= null) {
            throw CARDAPI_EXCEPTION;
        }
        return CARDAPI_WSDL_LOCATION;
    }

}
