
package com.guness.CardRegistery.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICardApi", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICardApi {


    /**
     * 
     * @param request
     * @return
     *     returns com.guness.CardRegistery.model.CardServiceResponse
     */
    @WebMethod(operationName = "RetrieveCardData", action = "http://tempuri.org/ICardApi/RetrieveCardData")
    @WebResult(name = "RetrieveCardDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetrieveCardData", targetNamespace = "http://tempuri.org/", className = "com.guness.CardRegistery.model.RetrieveCardData")
    @ResponseWrapper(localName = "RetrieveCardDataResponse", targetNamespace = "http://tempuri.org/", className = "com.guness.CardRegistery.model.RetrieveCardDataResponse")
    public CardServiceResponse retrieveCardData(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        RetrieveCardByAccountServiceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.guness.CardRegistery.model.ValidateCardServiceResponse
     */
    @WebMethod(operationName = "ValidateCardData", action = "http://tempuri.org/ICardApi/ValidateCardData")
    @WebResult(name = "ValidateCardDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidateCardData", targetNamespace = "http://tempuri.org/", className = "com.guness.CardRegistery.model.ValidateCardData")
    @ResponseWrapper(localName = "ValidateCardDataResponse", targetNamespace = "http://tempuri.org/", className = "com.guness.CardRegistery.model.ValidateCardDataResponse")
    public ValidateCardServiceResponse validateCardData(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        ValidateCardDataServiceRequest request);

}
